### PR TITLE
Added the jupyter notebook on the stoichiometric subspace

### PR DESCRIPTION
**Pull request by deanzimucha**
I added a conditional 'if' statement at the beginning of the code to put
the user input in a list if it's not. And I also raised an exception  if
the no. of components is not consistent.

The code is not yet completely bug-free for all possible user inputs.

### CODE REVIEW

**Comment by d-ming** [comment]
Nice, can you clean up the comments and then add it to artools.py?

**Comment by d-ming** [comment]
Actually, I've noticed a few bugs we need to address before we can merge into `artools.py`.

- The check for the length of the feed vector is indented to the same level as the flatten. That means the dimension check only occurs if `Cf0` is also a matrix. But if we supply a list of 1-D numpy arrays, this will bypass the check. The function will still fail later down the line, but it's difficult to see from the current error. I tried to put this in and it failed (the 3d van de vusse system):
```
stoich_mat = sp.array([[-1, 1, 0, 0], [0, -1, 1, 0], [-2, 0, 0, 1]]).T

Cf1 = sp.array([1, 0, 0])
Cf2 = sp.array([1.5, 0.1, 0, 0])
Cf3 = sp.array([0.5, 0.5, 0.5, 0.5])
Cf0s = [Cf1, Cf2, Cf3]

stoich_subspace(Cf0s, stoich_mat)
```
- The function is still not complete because we need to find the convex hull of all the points. The function currently just returns a stacked list of the vertices, but some of these points may be redundant. We also need to return both the combined list as well at the subspaces corresponding to each feed.

**Comment by deanzimucha** [comment]
@d-ming I brushed up on the comments in the code. I also modified the if statement
to calculate the vertices for a single feed because "if the stoich_mat is a 1D numpy array then an error is returned for 'stoich_mat.shape[1]`. 

And I added an if statement for computation of the convexHull of vertices in the overall stoichiometric subspace.

**Comment by d-ming** [comment]
OK great, thanks for doing this. 

I looked over the code and noticed that we don't need to do this check if we move the `stoich_mat` conversion to 2D up and hence force `stoich_mat` to always be 2D irrespective of how it's passed into the function. I made a small commit with the change, see: 13a73a7f1f5dd04dca3505157d3b25a8f795a2ee

Also, the test with 3 components and 2 reactions doesn't work for me. The coefficient matrix produces an unbounded region, actually. It has to do with the fact that `con2vert()` can't find an interior point (as described in #2). I'm trying to make improvements to `con2vert()` here: 6513a701c8268c4f9fa8050fc0407013712dbbab

**Comment by deanzimucha** [comment]
Okay great! I noticed the change, it makes it much easier to execute the
rest of the code.

**Pull request merged**
